# Generated by Django 4.1.1 on 2022-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
